services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python -m uvicorn main:app --host=0.0.0.0 --port=$PORT"
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - my_network  

networks:  
  my_network:
    driver: bridge

volumes:
  postgres_data: 